config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :customers

  resources :products

  devise_for :users
   root 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :name,
    presence: true
  
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { maximum: 100 }

  validates :document_number,
    presence: true,
    numericality: true,
    uniqueness: true

  validates :document_type,
    presence: true
    
end

app/models/event.rb
class Event < ActiveRecord::Base

    validates :name,
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { maximum: 100 }


    validates_presence_of :start_date, :end_date

    validate :end_date_is_after_start_date

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?
    if end_date < start_date
      errors.add :base, I18n.t('end_date_greater_then_start_date')
    end 
  end    

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  validates :code,
    presence: true,
    uniqueness: { case_sensitive: false }
  
  validates :name,
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { maximum: 100 }

  validates :price,
    presence: true,
    numericality: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all 
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :document_number, :document_type, :phone_area_code, :phone_number, :mobile_phone_area_code, :mobile_phone_number)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to action: "index", notice: 'Evento criado com sucesso' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to action: "index", notice: 'Evento atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_date, :end_date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :format_price, :only => [ :create, :update ]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Produto criado com sucesso.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Produto apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :name, :price)
    end
  
    def format_price
      @price = params[:product][:price];
      params[:product][:price] = @price.gsub('.','').gsub(',','.').gsub('R$ ','');
      Rails.logger.error params[:product][:price]
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def br_date_format date
      if date
        date.strftime("%d/%m/%Y")
      else
         " "
      end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :document_number %><br>
    <%= f.number_field :document_number %>
  </div>
  <div class="field">
    <%= f.label :document_type %><br>
    <%= f.number_field :document_type %>
  </div>
  <div class="field">
    <%= f.label :phone_area_code %><br>
    <%= f.text_field :phone_area_code %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :mobile_phone_area_code %><br>
    <%= f.text_field :mobile_phone_area_code %>
  </div>
  <div class="field">
    <%= f.label :mobile_phone_number %><br>
    <%= f.text_field :mobile_phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Document number</th>
      <th>Document type</th>
      <th>Phone area code</th>
      <th>Phone number</th>
      <th>Mobile phone area code</th>
      <th>Mobile phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.document_number %></td>
        <td><%= customer.document_type %></td>
        <td><%= customer.phone_area_code %></td>
        <td><%= customer.phone_number %></td>
        <td><%= customer.mobile_phone_area_code %></td>
        <td><%= customer.mobile_phone_number %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Document number:</strong>
  <%= @customer.document_number %>
</p>

<p>
  <strong>Document type:</strong>
  <%= @customer.document_type %>
</p>

<p>
  <strong>Phone area code:</strong>
  <%= @customer.phone_area_code %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @customer.phone_number %>
</p>

<p>
  <strong>Mobile phone area code:</strong>
  <%= @customer.mobile_phone_area_code %>
</p>

<p>
  <strong>Mobile phone number:</strong>
  <%= @customer.mobile_phone_number %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %> <% if @event.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@event.errors.count, "error") %> prohibited this
		event from being saved:</h2>

	<ul>
		<% @event.errors.full_messages.each do |message| %>
		<li><%= message %></li> <% end %>
	</ul>
</div>
<% end %>

<div class="col-lg-4 form-group" style="width">
	<div class="field">
		<%= f.label :name %><br> <%= f.text_field :name, :class => 'form-control' %>
	</div>
	<div class="field">
		<%= f.label :start_date %><br> 
		<%= f.text_field :start_date, :value => br_date_format(@event.start_date) , :class => "datepicker form-control" %>
	</div>
	<div class="field">
		<%= f.label :end_date %><br> 
		<%= f.text_field :end_date, :value => br_date_format(@event.end_date) , :class => "datepicker form-control" %>
	</div><br/>
	<div class="actions">
		<%= f.submit :class=> "btn btn-primary  btn-sm", :value=> "Salvar evento" %> 
		<%= link_to 'Voltar', events_path, :class=> "btn btn-primary  btn-sm" %></div>
	<% end %>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$(".datepicker").datepicker({
			dateFormat: "dd/mm/yy"
		});
	});
</script>

app/views/events/edit.html.erb
<h1>Editando evento</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventos Cadastrados</h1>

<div id="wrapper" style="width: 70%" >
	<div class="actionBar"><%= link_to 'Novo Evento', new_event_path, class: 'btn btn-primary btn-sm' %></div>
	
	<table class="table table-striped table-hover " style="width:100%">
	  <thead>
	    <tr>
	      <th>Nome</th>
	      <th>Data início</th>
	      <th>Data fim</th>
	      <th></th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @events.each do |event| %>
	      <tr>
	        <td><%= event.name %></td>
	        <td><%= br_date_format(event.start_date) %></td>
	        <td><%= br_date_format(event.end_date) %></td>
	        <td class="row-action">
	        	<%= link_to 'Editar', edit_event_path(event), :class=>'btn btn-primary btn-xs'  %>&nbsp;
	        	<%= link_to 'Apagar', event, method: :delete, :class=>'btn btn-primary btn-xs',  data: { confirm: 'VocÊ tem certeza?' } %>&nbsp;
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

app/views/events/new.html.erb
<h1>Novo Evento</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

app/views/home/index.html.erb
<h2>Evento Pontual</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Evento Pontual</title> 
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %> 
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<!--header start-->
	<header class="header black-bg">
		<div class="sidebar-toggle-box">
             <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
         </div>
		<a href="/" class="logo"><b>EVENTO PONTUAL</b></a>
		<div class="top-menu">
			<ul class="nav pull-right top-menu">
				<li><a class="logout" href="login.html">Logout</a></li>
			</ul>
		</div>
	</header>
	<aside>
		<div id="sidebar" class="nav-collapse ">
			<!-- sidebar menu start-->
			<ul class="sidebar-menu" id="nav-accordion">
				<li class="mt"><%= link_to "Eventos",events_path %></li>
				<li class="mt"><%= link_to "Produtos",products_path %></a></li>
				<li class="mt"><%= link_to "Clientes",customers_path %></li>
				<li class="mt"><a href="index.html"><span>Movimentação</span></a></li>
				<li class="mt"><a href="#contact"><span>Configurações</span></a></li>
			</ul>
			<!-- sidebar menu end-->
		</div>
	</aside>
	<section id="main-content">
		<section class="wrapper"><%= yield %></section>
	</section>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %> <% if @product.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@product.errors.count, "erro(s)") %> impediram que
		o produto fosse salvo.:</h2>

	<ul>
		<% @product.errors.full_messages.each do |message| %>
		<li><%= message %></li> <% end %>
	</ul>
</div>
<% end %>

<div class="col-lg-4 form-group" style="">
	<div class="field">
		<%= f.label :code %><br> <%= f.text_field :code, :class => 'form-control' %>
	</div>
	<div class="field">
		<%= f.label :name %><br> <%= f.text_field :name, :class => 'form-control' %>
	</div>
	<div class="field">
		<%= f.label :price %><br> <%= f.text_field :price, :id => 'price', :class => 'form-control money' %>
	</div><br/>
	<div class="actions">
		<%= f.submit :class=> "btn btn-primary btn-sm", :value=> "Salvar produto" %> 
		<%= link_to 'Voltar', products_path, :class=> "btn btn-primary  btn-sm" %></div>
	</div>
	<% end %>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('.money').maskMoney({decimal: ',', thousands : '.', prefix: 'R$ '});
	})
</script>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<div id="wrapper" style="width: 70%">
	<div class="actionBar"><%= link_to 'Novo produto', new_product_path, :class=>'btn btn-primary btn-sm' %></div>

	<table class="table table-striped table-hover " style="width: 100%">
		<thead>
			<tr>
				<th>Código</th>
				<th>Nome</th>
				<th>Preço</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @products.each do |product| %>
			<tr>
				<td><%= product.code %></td>
				<td><%= product.name %></td>
				<td><%= product.price %></td>
				<td class="row-action">
					<%= link_to 'Editar', edit_product_path(product), :class=>'btn btn-primary btn-xs' %> 
					<%= link_to 'Apagar', product, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-primary btn-xs' %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>